### DISCUSSION TITLE
如何指定自己的许可密钥

### DISCUSSION THREAD

**Discussion by chatfish11** [vvbbnn00/WARP-Clash-API#90] [Q&A] [answered]
如何指定自己的许可密钥，我领取了大量流量的密钥，我希望使用它来转换为节点

**Comment by vvbbnn00** [comment]
你好，由于目前该项目并没有直接的功能支持此操作，您可以根据以下步骤操作。

1. 编译并运行本项目
2. 下载[wgcf](https://github.com/ViRb3/wgcf/releases/tag/v2.2.19)
4. 在命令行，输入`wgcf register`，注册新用户
5. 在程序同目录下，找到`wgcf-account.toml`文件，格式如下：
```toml
access_token = '对应token'
device_id = '对应account_id'
license_key = '对应license_key'
private_key = '对应private_key'
```
6. 将其中的`license_key`修改为您的`license_key`，保存文件，执行`wgcf update`。
7. 重新打开`wgcf-account.toml`文件，获取更新后的上文中的字段。
8. 停止项目，在本项目目录下`account/account.json`，替换用户的`token`、`account_id`、`private_key`、`license_key`四个字段，对应关系见步骤5，保存后重启项目。

希望这对你有帮助！
