### ISSUE TITLE
希望能直接从dockerhub直接拉镜像运行

### ISSUE THREAD

**Issue by fantasyxby** [vvbbnn00/WARP-Clash-API#25]
有些机器在本地构建镜像不太方便，比如白群😂

**Comment by vvbbnn00** [comment]
已经增加了GitHub Action来编译并推送Docker镜像，可在`vvbbnn00/warp-clash-api`拉取镜像。

[https://hub.docker.com/r/vvbbnn00/warp-clash-api](https://hub.docker.com/r/vvbbnn00/warp-clash-api)

**Comment by SUGARYeUNGG** [comment]
讲真，想弄，但是没接触过，能不能出一个详细的教程。

**Comment by sukbearai** [comment]
部署失败了，可否出一个教程？

**Comment by pandamelive** [comment]
大神来一个教程

**Comment by Kaol-Fu** [comment]
有人pull image成功的么？我pull其它的image没问题，但是pull这个就会提示“tls: failed to verify certificate: x509: certificate is valid”。

**Comment by hanxi** [comment]
可以这样配置，新建文件 docker-compose.yaml ，写入以下内容:
```yaml
services:
  warp-clash:
    container_name: warp-clash
    image: vvbbnn00/warp-clash-api
    ports:
      - "21001:3000"
    environment:
      SECRET_KEY: 123456
    volumes:
      - ./logs:/app/logs
 ```
然后执行 `docker compose up -d` 启动。
访问 `http://你的IP:21001` ，输入SECRET_KEY（上面配的是123456，若没有配置，则可以留空），即可获取订阅链接。
