### ISSUE TITLE
按照说明用docker安装了之后，无法成功运行，帮忙看看是什么原因。

### ISSUE THREAD

**Issue by sarsmark-git** [vvbbnn00/WARP-Clash-API#47]
log的内容为：

FileNotFoundError: [Errno 2] No such file or directory: './config/cf-config.json'
/usr/local/lib/python3.11/site-packages/tzlocal/unix.py:193: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
2024-02-22 08:08:22,353 - INFO - Start scheduler
Traceback (most recent call last):
  File "/app/app.py", line 82, in <module>
    main()
  File "/app/app.py", line 54, in main
    from services.web_service import createApp
  File "/app/services/web_service.py", line 6, in <module>
    from services.subscription import generateClashSubFile, generateWireguardSubFile, generateSurgeSubFile
  File "/app/services/subscription.py", line 18, in <module>
    CF_CONFIG = json.load(open("./config/cf-config.json", "r", encoding="utf8"))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './config/cf-config.json'

**Comment by sarsmark-git** [comment]
另外docker有没有通过cli安装，或者用docker-compose安装（不需要手动编译那种）的方式。谢谢。

**Comment by vvbbnn00** [comment]
您可以使用下面的`docker-compose`文件来进行部署（记得预先在部署的文件夹内创建`account`和`logs`子文件夹）

```yaml
version: "3.8"
services:
  warp-clash:
    image: vvbbnn00/warp-clash-api:latest
    ports:
      - "21001:3000"
    env_file:
      - .env.local
    volumes:
      - ./account:/app/account
      - ./logs:/app/logs
```
